services:
  - name: salesdata
    type: web
    build:
      docker:
        file: salesdata/Dockerfile
        context: .
    run:
      env:
        - name: PORT
          value: "8080"
      command: sh -c "uvicorn app:app --host 0.0.0.0 --port ${PORT}"
    ports:
      - 8080
