services:
  - name: salesdata
    type: web
    build:
      docker:
        file: salesdata/Dockerfile
        context: .
    run:
      env:
        - name: PORT
          value: "8080"
    ports:
      - 8080
